### ISSUE TITLE
Notification of Twitch Export Failures

### ISSUE THREAD

**Issue by kacollins** [techlahoma/infrastructure-committee#2]
Would it be possible for the content creation committee to get notifications of emails sent to Techlahoma with the subject line `Your Twitch export to YouTube failed`? I think a simple filter and forward to broadcasting at techlahoma dot org would do the trick. Thanks!

**Comment by DevinClark** [comment]
I created a filter in the techlahoma@gmail.com account for this subject line and had it forward to broadcasting@techlahoma.org.
