### ISSUE TITLE
YouTube requires verification to associate techlahoma.org by webpage upload.

### ISSUE THREAD

**Issue by Archyver** [techlahoma/infrastructure-committee#3]
While signed in as techlahoma or a manager of the Youtube channel visit 
https://www.youtube.com/advanced_settings?ar=3&nv=1 , scroll down to below section and click Verify.
![image](https://user-images.githubusercontent.com/26891933/59304111-9de31000-8c65-11e9-8d85-32ff5d254716.png)

Will proceed to request the following

Recommended: HTML file upload
Upload an HTML file to your site.

1. Download this HTML verification file. [XXXXXXXX.html]
2. Upload the file to http://techlahoma.org/
3. Confirm successful upload by visiting http://techlahoma.org/XXXXXXXXX.html in your browser.
4. Click Verify below.
To stay verified, don't remove the HTML file, even after verification succeeds.

Alternate methods also listed:

- HTML tag
Add a meta tag to your site's home page.
- Domain name provider
Sign in to your domain name provider.
- Google Analytics
Use your Google Analytics account.
- Google Tag Manager
Use your Google Tag Manager account.

**Comment by kacollins** [comment]
Any updates on this? @DevinClark?

**Comment by DevinClark** [comment]
I completed this via the 'Domain name provider' option using a TXT record on our DNSimple account.

![image](https://user-images.githubusercontent.com/353563/66760177-333a1f00-ee67-11e9-9902-85504bbc18ea.png)

Closing the issue. Feel free to reopen if there are any questions or concerns.
